### ISSUE TITLE
Jobs are not updating. 

### ISSUE THREAD

**Issue by RahulSihara** [pittcsc/Summer2023-Internships#3590] opened 2024-01-30 15:49 UTC
Hey, job postings are stuck after 24th Jan. I am not able to find any new opportunities. 
Any idea why?

**Comment by poornimajd** [comment] 2024-01-30 16:50
Same here, I haven't received any new mails from 25th Jan, when will it be restored again?

**Comment by rushilsrivastava** [comment] 2024-01-31 20:23
duplicate of #3589 - we're looking in it

**Closed as completed by rushilsrivastava** 2024-01-31 20:23 UTC
