### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by andrewhong04** [pittcsc/Summer2023-Internships#2412] opened 2023-08-26 13:19 UTC
### Link to Internship Posting

https://careers-chickfila.icims.com/jobs/14373/dtt-software-engineering-summer-2024-intern/job?utm_source=Simplify&ref=Simplify

### Company Name

Chick-fil-A

### Internship Title

Software Engineering Intern

### Location

Atlanta, GA

### Does this internship offer sponsorship?

None

### Is this internship currently accepting applications?

None

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Email associated with your GitHub account (Optional)

andrew.jwn.hong@gmail.com

### Reason for edit

no longer accepting applications

**Comment by hemanthy1** [comment] 2023-08-26 18:05
Duplicate of #2411

**Closed as completed by hemanthy1** 2023-08-26 18:05 UTC
Labels: edit_internship
