### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by cwcoogan** [pittcsc/Summer2023-Internships#2224] opened 2023-08-09 19:52 UTC
### Link to Internship Posting

https://paypal.eightfold.ai/careers?query=R0106013&pid=274895391783&domain=paypal.com&sort_by=relevance

### Company Name

PayPal

### Internship Title

Software Engineering Intern

### Location

US

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

chasecoogan12@gmail.com

**Comment by hemanthy1** [comment] 2023-08-09 20:53
This is a duplicate of #2222

**Closed as completed** 2023-08-09 21:15 UTC
Labels: new_internship
