### ISSUE TITLE
Editing Internship

### ISSUE THREAD

**Issue by 7878k** [pittcsc/Summer2023-Internships#2225] opened 2023-08-09 21:17 UTC
### Link to Internship Posting

https://careers.mitre.org/us/en/job/MITRUSR111593EXTERNALENUS/Computer-Science-and-Software-Engineering-Intern-positions?utm_source=SimplifyGH&ref=Simplify

### Company Name

MITRE 

### Internship Title

Computer Science and Software Engineering Intern

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Remove this internship from the list?

- [ ] Yes, remove this internship

### Reason for edit

The webpage says: Capable of obtaining and maintaining a Secret Clearance, so it means not to offer sponsorship.

**Comment by hemanthy1** [comment] 2023-08-09 21:20
This is a duplicate of #2220

**Closed as completed** 2023-08-09 22:54 UTC
Labels: edit_internship
